language: node_js
node_js:
  - node
notifications:
  email: false

#
# precise does not have wine1.6-i386
#  it would be necessary to add wine ppa
#
# https://docs.travis-ci.com/user/trusty-ci-environment/#Using-Trusty
dist: bionic
sudo: required

before_install:
  - npm i -g coffee-script

before_deploy:
  # YAKYAK_VERSION is used in the files to copy
  - export YAKYAK_VERSION=`node -e "console.log(require('./package.json').version);"`
  # debug information for the electron packager
  - export DEBUG=electron-packager
  # allows to have wine with 32-bits
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo rm /var/lib/dpkg/lock
  - sudo apt-get install -y -qq wine-stable zip xvfb
  - wine wineboot --init # WINEARCH=win32
  #
  # actuall building of the binaries
  - npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:linux-x64
  - npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:linux-ia32
  - npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:darwin
  - xvfb-run npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:win32
  #
  # RPM and DEB binaries
  # install fpm
  - gem install --no-document fpm
  # needed to deploy on rpm / pacman
  - sudo apt-get install -y -qq rpm libarchive-tools
  #
  - npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-x64:rpm:nodep
  - npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-x64:deb:nodep
  - npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-x64:pacman:nodep
  - npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-ia32:rpm:nodep
  - npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-ia32:deb:nodep
  - npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-ia32:pacman:nodep
  #
  # Flatpak
  # install flatpak dependencies
  #
  # Commented out as it is not working
  #
  #- sudo add-apt-repository ppa:alexlarsson/flatpak -y
  #- sudo apt-get update -qq
  #- sudo apt-get install flatpak-builder flatpak -qq
  #- flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  ## 64-bits
  #- flatpak --user install flathub org.freedesktop.Sdk/x86_64/1.6
  #- flatpak --user install flathub org.freedesktop.Platform/x86_64/1.6
  ## 32-bits
  #- flatpak --user install flathub org.freedesktop.Sdk/i386/1.6
  #- flatpak --user install flathub org.freedesktop.Platform/i386/1.6
  #
  #- npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-x64:flatpak:nodep
  #- npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-ia32:flatpak:nodep

deploy:
  provider: releases
  # overwrite pre-existing files
  overwrite: true
  # always create a pre-release
  prerelease: true
  # necessary to deploy in github, otherwise it would clean everything
  skip_cleanup: true
  # secret API_KEY stored in Travis CI
  api_key: "${API_KEY}"
  # files to copy to github release
  file:
    - "dist/yakyak-${YAKYAK_VERSION}-linux-x64.tar.gz"
    - "dist/yakyak-${YAKYAK_VERSION}-linux-x86_64-pacman.tar.gz"
    - "dist/yakyak-${YAKYAK_VERSION}-linux-ia32-pacman.tar.gz"
    - "dist/yakyak-${YAKYAK_VERSION}-linux-ia32.tar.gz"
    - "dist/yakyak-${YAKYAK_VERSION}-win32-ia32.zip"
    - "dist/yakyak-${YAKYAK_VERSION}-win32-x64.zip"
    - "dist/yakyak-${YAKYAK_VERSION}-osx.zip"
      #- "dist/com.github.yakyak.YakYak_master_x64.flatpak"
      #- "dist/com.github.yakyak.YakYak_master_ia32.flatpak"
    - "dist/yakyak-${YAKYAK_VERSION}-linux-amd64.deb"
    - "dist/yakyak-${YAKYAK_VERSION}-linux-i386.deb"
    - "dist/yakyak-${YAKYAK_VERSION}-linux-i386.rpm"
    - "dist/yakyak-${YAKYAK_VERSION}-linux-x86_64.rpm"
  # only trigger on tags
  on:
    tags: true
